# Development environment Docker Compose

services:
  backend:
    build:
      context: ./backend/HotelWebsiteBuilder
      dockerfile: Dockerfile.dev
    container_name: hotel-website-builder-backend-dev
    ports:
      - "7001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./backend/HotelWebsiteBuilder:/app
      - /app/bin
      - /app/obj
    networks:
      - hotel-website-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/hotel-website-builder
      dockerfile: Dockerfile.dev
    container_name: hotel-website-builder-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:7001/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/hotel-website-builder:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hotel-website-network
    restart: unless-stopped

networks:
  hotel-website-network:
    driver: bridge

volumes:
  hotel-data: 